### PR TITLE
AIRO-1654 fixed cpu error

### PR DESCRIPTION
**Pull request by JonathanLeban**
## Proposed change(s)

Describe the changes made in this PR.

Fixed a cpu/gpu error made during the inference.

### CODE REVIEW

**Review by at669 — APPROVED** [review]
Tested and works on my machine. Will follow-up if problem persists on other devices.

**Comment by at669** [comment]
Linked to #45.

**Comment by adakoda** [comment]
Thank you for your work.

I had tested your code changes.
But my cuda 11.6 gou environment could not solve the problem without adding following patch.

 `add caling model.to(device) after calling model.load_state_dict()`

**Comment by at669** [comment]
> Thank you for your work.
> 
> I had tested your code changes. But my cuda 11.6 gou environment could not solve the problem without adding following patch.
> 
> `add caling model.to(device) after calling model.load_state_dict()`

Thank you for the feedback @adakoda. Could you please pull down #52 and rerun to see if this resolves your issue?

**Pull request merged**
