### PR TITLE
Use TGS solver

### PR DESCRIPTION
**Pull request by peifeng-unity**
## Proposed change(s)

Ignore the collisions on the inner knuckles so that the TGS solver will work.

Fix a bug related to Ubuntu package installation when building the docker image. [[Issue](https://github.com/Unity-Technologies/Unity-Robotics-Hub/issues/240)]

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [x] Other: enable to use TGS solver

## Testing and Verification

Tested the Pose Estimation Quick Demo with the TGS solver

### Test Configuration:
- Unity Version: Unity 2020.2.6f1

https://user-images.githubusercontent.com/56408141/120538136-f8b62a80-c39a-11eb-854d-b00a9acfc77e.mov

## Checklist
- [x] Ensured this PR is up-to-date with the target branch
- [x] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/CONTRIBUTING.md)
- [x] Added tests that prove my fix is effective or that my feature works
- [x] Updated the [Changelog](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/CHANGELOG.md#unreleased)
- [x] Updated the documentation as appropriate

## Other comments

### CODE REVIEW

**Review by at669 — COMMENTED** [review]
thanks for checking out this issue! out of curiosity, do we know why the gripper doesn't reset to an upright position, but looks around 90º rotated instead?

i also think the following things need to be updated with respect to the collision changes:
- [ ] [TutorialAssets.zip](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/releases/tag/v0.0.1)
- [ ] Create a new Project part of the tutorial (add TGS step?) in [Part 1](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/Documentation/1_set_up_the_scene.md#step-1)

**Comment by peifeng-unity** [comment]
Ah, good question! My guess is that the rotate speed might be too slow with the TGS solver. I will take a look

**Comment by peifeng-unity** [comment]
> thanks for checking out this issue! out of curiosity, do we know why the gripper doesn't reset to an upright position, but looks around 90º rotated instead?
> 
The issue was caused by the order of the articulation bodies under `base_link`. There are two parallel child articulation bodies in `base_link`, the `shoulder_link` and the `base`. To reset the joints to the original pose, [the code](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/PoseEstimationDemoProject/Assets/TutorialAssets/Scripts/TrajectoryPlanner.cs#L135) only want to manipulate the `should_link` and its child articulation bodies.  In the current scene, the `base` is after `shoulder_link` so it matches the indices. But when importing the robot from the urdf file on my laptop, the order is reversed so that the code will manipulate `base` link and ignore the last joint `wrist_3_link` so that the gripper doesn't return to it original position.

The issue is fixed by using the `jointArticulationBodies` rather than the `articulationBodyChain`.

**Comment by peifeng-unity** [comment]
> i also think the following things need to be updated with respect to the collision changes:
> 
> * [ ]  [TutorialAssets.zip](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/releases/tag/v0.0.1)

Sure, do we want to create a new release or only replace the zip file? I can update it once the PR is merged

**Comment by peifeng-unity** [comment]
The new test with TGS solver after fixing the bugs

https://user-images.githubusercontent.com/56408141/120851405-a48f7f80-c52d-11eb-89dc-825705b7efce.mov

**Review by at669 — APPROVED** [review]
tested and works on my machine as well! lgtm

> Sure, do we want to create a new release or only replace the zip file? I can update it once the PR is merged

we've just been replacing the zip thus far!

**Comment by peifeng-unity** [comment]
> > Sure, do we want to create a new release or only replace the zip file? I can update it once the PR is merged
> 
> we've just been replacing the zip thus far!

Updated the TutorialAssets.zip file in the release.

**Pull request merged**
